version: "3.8"

services:
  database:
    image: postgres:16
    ports:
      - "32768:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=project-management-system